export const apiDevelopmentQuestions =  [
    { id:"api-1", 
      question:"Vilken HTTP-metod används för att skapa resurser?", 
      options:["GET","POST","PUT","DELETE"], 
      answerIndex:1 },
    { id:"api-2",
       question:"Vad betyder REST?",
        options:["Representational State Transfer","Random Event State Transfer","Remote Execution Standard","Reliable State Transport"],
         answerIndex:0 },
    { id:"api-3",
       question:"Vilken statuskod betyder 'Bad Request'?", 
       options:["200","400","401","500"],
        answerIndex:1 },
    { id:"api-4",
       question:"Vilken del av en URL anger resursens plats?", 
       options:["Querystring","Path","Header","Body"], 
       answerIndex:1 },
    { id:"api-5",
       question:"Vilken metod används för att uppdatera delar av en resurs?",
        options:["PUT","PATCH","POST","GET"], 
        answerIndex:1 },
    { id:"api-6",
       question:"Vilken standard används ofta för API-dokumentation?",
        options:["Swagger/OpenAPI","GraphQL","SOAP","RAML"],
         answerIndex:0 },
    { id:"api-7",
       question:"Vilken statuskod betyder 'Unauthorized'?", 
       options:["401","403","404","500"],
        answerIndex:0 },
    { id:"api-8",
       question:"Vilken header används för att ange klientens önskade format?", 
       options:["Accept","Content-Type","Authorization","Cache-Control"],
        answerIndex:0 },
    { id:"api-9",
       question:"Vilken metod används för att ta bort resurser?", 
       options:["DELETE","REMOVE","DROP","POST"], 
       answerIndex:0 },
    { id:"api-10", 
      question:"Vilken statuskod betyder 'Internal Server Error'?", 
      options:["400","401","403","500"],
       answerIndex:3 }
  ];