export const inputFormsQuestions =
 [
    { id:"form-1",
       question:"Vilket attribut gör ett inputfält obligatoriskt?",
        options:["required","mandatory","validate","must"], 
        answerIndex:0 },
    { id:"form-2",
       question:"Vilken input-type används för e-post?",
        options:["text","email","mail","string"], 
        answerIndex:1 },
    { id:"form-3",
       question:"Vilket attribut kopplar label till input?",
        options:["for","id","name","bind"], 
        answerIndex:0 },
    { id:"form-4",
       question:"Vilken input-type ger datumväljare?",
        options:["date","datetime","calendar","time"], 
        answerIndex:0 },
    { id:"form-5",
       question:"Vilket attribut används för att skicka förifyllt värde?",
        options:["value","default","preset","text"], 
        answerIndex:0 },
    { id:"form-6",
       question:"Vilken input-type används för lösenord?",
        options:["text","password","secure","hidden"],
         answerIndex:1 },
    { id:"form-7",
       question:"Vilket attribut används för att gruppera radioknappar?",
        options:["group","name","id","set"],
         answerIndex:1 },
    { id:"form-8",
       question:"Vilken input-type används för filuppladdning?",
        options:["file","upload","binary","attachment"],
         answerIndex:0 },
    { id:"form-9",
       question:"Vilket attribut anger maxlängd på textfält?",
        options:["maxlength","max","limit","size"],
         answerIndex:0 },
    { id:"form-10",
       question:"Vilken input-type används för kryssrutor?",
        options:["checkbox","radio","toggle","switch"], 
        answerIndex:0 }
  ];